Styleguide: casing in shell scripts
barsoom/devbook pull request #71
Opened 2021-11-18 08:08 UTC by henrik

Discussion: https://auctionet.slack.com/archives/CF9SAN79V/p1637165952079500

I don't think the env bit is controversial or really needs saying, but let's be extra explicit since we say to make others lowercase.

Did not mention shell variables, which are also typically capitalized, since they can be thought of as a kind of environment variable and we probably don't need to explicitly cover them.

(Going by the definition of env and shell variables here: https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-linux)

2021-11-18 08:09 UTC, olleolleolle approved these changes

2021-11-18 08:12 UTC, frederfred approved these changes

2021-11-19 09:06 UTC, p-wall requested changes
Nice that we add shell scripts to our styleguide!

2021-11-19 09:07 UTC, tskogberg approved these changes

2021-11-19 09:36 UTC, p-wall approved these changes

2021-11-29 10:35 UTC, p-wall commented
No feedback for a couple weeks, merging

2021-11-29 10:35 UTC, merged